version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432

  app:
    build: bot
    restart: always
    env_file: ./.env
    depends_on:
      - db